### ISSUE TITLE
Cannot run the development server on mac-tizy (Mac OS X)

### ISSUE THREAD

**Issue by gmacario** [hackafake/hackafake-dashboard#15]
I followed the instructions in the project `README.md` but obtained the following error:

```
gmacario@mac-tizy:~/github/hackafake/hackafake-dashboard (master)*$ ng serve
Local workspace file ('angular.json') could not be found.
Error: Local workspace file ('angular.json') could not be found.
    at WorkspaceLoader._getProjectWorkspaceFilePath (/usr/local/lib/node_modules/@angular/cli/models/workspace-loader.js:37:19)
    at WorkspaceLoader.loadWorkspace (/usr/local/lib/node_modules/@angular/cli/models/workspace-loader.js:24:21)
    at ServeCommand._loadWorkspaceAndArchitect (/usr/local/lib/node_modules/@angular/cli/models/architect-command.js:180:32)
    at ServeCommand.<anonymous> (/usr/local/lib/node_modules/@angular/cli/models/architect-command.js:47:25)
    at Generator.next (<anonymous>)
    at /usr/local/lib/node_modules/@angular/cli/models/architect-command.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (/usr/local/lib/node_modules/@angular/cli/models/architect-command.js:3:12)
    at ServeCommand.initialize (/usr/local/lib/node_modules/@angular/cli/models/architect-command.js:46:16)
    at Object.<anonymous> (/usr/local/lib/node_modules/@angular/cli/models/command-runner.js:87:23)
gmacario@mac-tizy:~/github/hackafake/hackafake-dashboard (master)*$
```

Running on mac-tizy:

* OS: macOS High Sierra Version 10.13.5
* Node.JS v8.11.3
* npm version 5.6.0
* Angular CLI

**Comment by gmacario** [comment]
The issue is no longer reproducible after merging PR #21 on master

```
gmacario@mac-tizy:~/github/hackafake/hackafake-dashboard (master)$ git log --oneline -1
08583f7 (HEAD -> master, origin/master, origin/HEAD) Fix build on Mac OS X (#21)
gmacario@mac-tizy:~/github/hackafake/hackafake-dashboard (master)$ node --version
v8.11.3
gmacario@mac-tizy:~/github/hackafake/hackafake-dashboard (master)$ npm --version6.1.0
gmacario@mac-tizy:~/github/hackafake/hackafake-dashboard (master)$ npm install
audited 9232 packages in 8.566s
found 17 vulnerabilities (1 low, 16 moderate)
  run `npm audit fix` to fix them, or `npm audit` for details
gmacario@mac-tizy:~/github/hackafake/hackafake-dashboard (master)$
gmacario@mac-tizy:~/github/hackafake/hackafake-dashboard (master)$ npm run ng build

> hackafake-dashboard@0.0.0 ng /Users/gmacario/github/hackafake/hackafake-dashboard
> ng "build"

Date: 2018-07-04T03:37:55.110Z                                                - Hash: a5af352a0c81399f862a
Time: 5264ms
chunk {inline} inline.bundle.js, inline.bundle.js.map (inline) 3.89 kB [entry] [rendered]
chunk {main} main.bundle.js, main.bundle.js.map (main) 13.7 kB [initial] [rendered]
chunk {polyfills} polyfills.bundle.js, polyfills.bundle.js.map (polyfills) 204 kB [initial] [rendered]
chunk {styles} styles.bundle.js, styles.bundle.js.map (styles) 14.7 kB [initial] [rendered]
chunk {vendor} vendor.bundle.js, vendor.bundle.js.map (vendor) 2.56 MB [initial] [rendered]

WARNING in ./src/app/dashboard/dashboard.component.scss
(Emitted value instead of an instance of Error) autoprefixer: /Users/gmacario/github/hackafake/hackafake-dashboard/src/app/dashboard/dashboard.component.scss:28:8: Can not find grid areas: logo, counter, faker, fakenews, footer
gmacario@mac-tizy:~/github/hackafake/hackafake-dashboard (master)$ npm run ng serve

> hackafake-dashboard@0.0.0 ng /Users/gmacario/github/hackafake/hackafake-dashboard
> ng "serve"

** NG Live Development Server is listening on localhost:4200, open your browser on http://localhost:4200/ **
Date: 2018-07-04T03:38:25.465Z                                                - Hash: 226a546194f835259f3b
Time: 5393ms
chunk {inline} inline.bundle.js (inline) 3.85 kB [entry] [rendered]
chunk {main} main.bundle.js (main) 34.3 kB [initial] [rendered]
chunk {polyfills} polyfills.bundle.js (polyfills) 554 kB [initial] [rendered]
chunk {styles} styles.bundle.js (styles) 42 kB [initial] [rendered]
chunk {vendor} vendor.bundle.js (vendor) 7.76 MB [initial] [rendered]

WARNING in ./src/app/dashboard/dashboard.component.scss
(Emitted value instead of an instance of Error) autoprefixer: /Users/gmacario/github/hackafake/hackafake-dashboard/src/app/dashboard/dashboard.component.scss:28:8: Can not find grid areas: logo, counter, faker, fakenews, footer

webpack: Compiled with warnings.
```

Closing issue
